---
title: "strings_and_factors"
author: "Xue Yang"
date: "10/11/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

Load some packages.

```{r}
library(rvest)
library(p8105.datasets)
```


### Regex

```{r}
# create a collection of string vector
string_vec = c("my", "name", "is", "jeff")

# scan through the string and look for something that match
str_detect(string_vec, "jeff")
str_detect(string_vec, "Jeff")

# scan through the string and look for the match and replace the match
str_replace(string_vec, "jeff", "Jeff")
str_replace(string_vec, "je", "Je") # also can be mathc and replace

# ?str_detect
```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think") # "i think whereever show up"
str_detect(string_vec, "^i think") # "i think" should be at the beginning
str_detect(string_vec, "i think$") # "i think" should be at the end
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH!!"
  )

# match upper or lower case of B and then followed by lower case of ush
str_detect(string_vec,"[Bb]ush") 

```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

# start with a number and followed by a letter (both upper and lower)
str_detect(string_vec, "^[0-9][a-zA-Z]") 

```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

# 7 and followed by anything and then 11 (The character . matches anything.)
str_detect(string_vec, "7.11") 

```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

# find match for "[" using "\\" (special characters)
str_detect(string_vec, "\\[") 
```


### PULSE data

Tidy the PULSE data!!

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  gather(key = visit, value = bdi, bdi_score_bl:bdi_score_12m) %>%
  mutate(
    # look through visit variable and replace the "bdi_score_" with nothing
    visit = str_replace(visit, "bdi_score_", ""),
    # scan through the new version of visit variable and replace "bl" with "00m"
         visit = str_replace(visit, "bl", "00m"),
    # treat the strings as a factor and relevel it as "00m", "01m", "06m", "12m"
         visit = fct_relevel(visit, str_c(c("00", "01", "06", "12"), "m"))) %>% 
  # might nothing change, but when use str()
 # $ visit: Factor w/ 4 levels "00m","01m","06m",..: 1 1 1 1 1 1 1 1 1 1 ...
  arrange(id, visit)
```


### NSDUH

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)

table_marj = (drug_use_xml %>% html_nodes(css = "table")) %>% 
  .[[1]] %>%
  html_table() %>%
  slice(-1) %>%
  as_tibble() 
```

clean up the imported data...

```{r}
data_marj = 
  table_marj %>%
  
  # remove any columns contain "P Value"
  select(-contains("P Value")) %>% 
  
  # make the all variables the other than "State" to be as the value of key
  gather(key = key, value = percent, -State) %>% 
  
  # separate age and year by "("
  separate(key, into = c("age", "year"), sep = "\\(") %>% 
  
  mutate(
    # replace ")" in year with nothing
    year = str_replace(year, "\\)", ""), 
    # replace "a" to "c" in percent which at end with nothing
    percent = str_replace(percent, "[a-c]$", ""), 
    percent = as.numeric(percent)) %>%
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```


Now that we have tidy data, we can make some plot!

```{r}
data_marj %>%
  filter(age == "12-17") %>% 
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


```{r}
data_marj %>%
  filter(age == "12-17") %>% 
  # reorder the state variable according to the median of percent variable
  mutate(State = fct_reorder(State, percent)) %>% 
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) # shift the text in axis-x 

```


```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

urls = str_c(url_base, 1:5) # get review from page 1 to 5

read_html(urls[1]) %>% 
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()
##  [1] "Go watch THE ROCK or dumb & dumber instead"
##  [2] "My mom loves it"                           
##  [3] "Nothing Quite Like It."                    
##  [4] "Has pretty sweet bow skills."              
##  [5] "Great"                                     
##  [6] "Fast delivery"                             
##  [7] "Lol"                                       
##  [8] "Very funny movie"                          
##  [9] "Vote For Pedro"                            
## [10] "So funny!"

read_html(urls[2]) %>% 
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()
##  [1] "Great move"                                      
##  [2] "Refund needed. Did not pay through Amazon prime."
##  [3] "Need a laugh?"                                   
##  [4] "The greatest!"                                   
##  [5] "Five Stars"                                      
##  [6] "Napoleon Dynamite is an awesome movie"           
##  [7] "One Star"                                        
##  [8] "\U0001f62b"                                      
##  [9] "Five Stars"                                      
## [10] "Haha"
```



### Factors...


```{r}
vec_sex = factor(c("male", "male", "female", "female")) 
# Since we don't specify which is the first category so R choose the level for what is the category 1 and what is category 2
as.numeric(vec_sex)

# recreate the reference of level to be "male"
vec_sex = relevel(vec_sex, ref = "male") 
vec_sex
as.numeric(vec_sex)
```


### Weather data

Here's the weather data again.

```{r, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```


```{r}
weather_df %>% 
  mutate(name = factor(name)) %>% pull(name)
```

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```

```{r}
weather_df %>%
  # fac_relevel: relevel the name variable and order them in a order you want "Waikiki_HA" fisrt, and then "CentralPark_NY", "Waterhole_WA"
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```

```{r}
weather_df %>%
  # fac_reorder : reorder the name variable with the median of tmax variable
  # this is what we often use to make the plot more clearly!!!
  mutate(name = forcats::fct_reorder(name, tmax)) %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```

### Linear regression

```{r}
weather_df %>%
  lm(tmax ~ name, data = .)
```

```{r}
weather_df %>%
  # treat "Waikiki_HA" as a reference category
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  lm(tmax ~ name, data = .)
```


### NYC Restuarant Inspections 

```{r}
data(rest_inspec)

rest_inspec %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)
```

Make my life easy by 

```{r}
rest_inspec =
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))
```

Pizza places.

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "Pizza")) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)
```

```{r}
library(viridis)
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() + # bar plot be sepreated by boro and fill by grade
  scale_fill_viridis(discrete = TRUE)
```

Reorder ...

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(boro = fct_relevel(boro, "Staten Island")) %>% 
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = TRUE)
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  # take the order of how frequenly they are appreared (descending number)
  mutate(boro = fct_infreq(boro)) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = TRUE)
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(boro = fct_infreq(boro),
         # anywhere you see "Brooklyn" replace with "HipsterHQ"
         boro = replace(boro, which(boro == "Brooklyn"), "HipsterHQ")) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = TRUE)


## Warning message:
## In `[<-.factor`(`*tmp*`, list, value = "HipsterHQ") :
## invalid factor level, NA generated

# it is not allowed in factor level
```

Really change factor values...

```{r}
rest_inspec %>% 
  filter(str_detect(dba, regex("pizza", ignore_case = TRUE))) %>%
  mutate(boro = fct_infreq(boro),
         # using fct_recode to add the level "HipsterHQ" and replace level "Brooklyn"
         boro = fct_recode(boro, "HipsterHQ" = "Brooklyn")) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() + 
  scale_fill_viridis(discrete = TRUE)
```


